### ISSUE TITLE
Periodic stack trace causes Fatal error exit

### ISSUE THREAD

**Issue by robacarp** [jaytaph/switchbox#27]
Cheers!

During a telehash demo at a meetup, I download and fired up the php switch. Periodically, the switch would exit with the following stack trace:

```
PHP Fatal error:  Uncaught exception 'DomainException' with message 'couldn't decrypt open' in /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Packet/Open.php:34
Stack trace:
#0 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Iface/Telehash.php(87): SwitchBox\Packet\Open->process(Object(SwitchBox\Packet))
#1 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Iface/Telehash.php(48): SwitchBox\Iface\Telehash->_handleSocket(Resource id #22)
#2 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/SwitchBox.php(156): SwitchBox\Iface\Telehash->handle(Object(SwitchBox\SwitchBox), Resource id #22)
#3 /Users/r/Documents/Programs/php/switchbox/app.php(26): SwitchBox\SwitchBox->loop()
#4 {main}
  thrown in /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Packet/Open.php on line 34

Fatal error: Uncaught exception 'DomainException' with message 'couldn't decrypt open' in /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Packet/Open.php:34
Stack trace:
#0 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Iface/Telehash.php(87): SwitchBox\Packet\Open->process(Object(SwitchBox\Packet))
#1 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/Iface/Telehash.php(48): SwitchBox\Iface\Telehash->_handleSocket(Resource id #22)
#2 /Users/r/Documents/Programs/php/switchbox/lib/SwitchBox/SwitchBox.php(156): SwitchBox\Iface\Telehash->handle(Object(SwitchBox\SwitchBox), Resource id #22)
#3 /Users/r/Documents/Programs/php/switchbox/app.php(26): SwitchBox\SwitchBox->loop()
#4 {main}
```

**Comment by jaytaph** [comment]
Thanks for the report. Can you remember which node this was coming from? Was this also a PHP switch, or a node.js or something else? Might make it easier to reproduce.

**Comment by robacarp** [comment]
Heh, well. All of them? :\

We were trying to test as many on a network as possible, so we had nearly every library running that would go.
